### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jdfreder** [vaultjs/design#1]
Here's my proposal:

![logo](https://cloud.githubusercontent.com/assets/3292874/11372930/df4cdf6e-9284-11e5-95a4-0fa1d5edf767.png)

I've purposefully left out the colors.

**Comment by rgbkrk** [comment]
I'd love to see the vault tec logo inset inside of a hexagon, likely with pipboy green.

**Comment by rgbkrk** [comment]
In the interim, I've posted this as the github logo because we need a square one:

![pipboy](https://cloud.githubusercontent.com/assets/836375/11374807/9a0a5c4c-929d-11e5-893a-bb9ae5930a9f.jpg)

**Comment by jdfreder** [comment]
![logo](https://cloud.githubusercontent.com/assets/3292874/11375730/ac445e50-9291-11e5-93cc-af48f03b9f17.png)

**Comment by jdfreder** [comment]
![logo](https://cloud.githubusercontent.com/assets/3292874/11375816/46dc9ed2-9292-11e5-86e9-e5cadfa9f6b4.png)

**Comment by jdfreder** [comment]
![logo](https://cloud.githubusercontent.com/assets/3292874/11376288/bb2b3ce2-9294-11e5-948b-695b1496d501.png)

**Comment by rgbkrk** [comment]
Loving these. I prefer single color on the vault tec logo and the darker green hexagon.
